## Numpy

In [1]:
import numpy as np

1. Создайте вектор состоящий из чисел от 0 до 11 включительно. 

In [124]:
vec = np.arange(12)
vec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

2. Измените размерность вектора и превратите его в матрицу 3 х 4

In [125]:
matrix = vec.reshape((3,4))
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

3. Найдите произведение полученной матрицы и вектора [2, 3, 5, 6]

In [126]:
other_vec = np.array([ 2, 3, 5, 6])
matrix.dot(other_vec)

array([ 31,  95, 159])

4. Из матрицы из пункта 2 сделайте квадратную матрицу состоящую из строк с индексами 0, 1, 3

In [127]:
new_mat = matrix [:, [0,1,3]]
new_mat

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

5. Найдите обратную матрицу к полученной в пункте 4.

In [128]:
new_mat_inv = np.linalg.inv(new_mat)

LinAlgError: Singular matrix

6. Проверьте является ли она обратной?

In [129]:
new_mat_inv.dot(new_mat)

array([[ 1.  ,  0.25, -1.25],
       [-1.  , -0.25,  1.25],
       [ 0.  ,  0.  ,  0.5 ]])

## Pandas

In [13]:
import pandas as pd

1. Загрузите данные из https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv в DataFrame. Воспользуйтесь одним из способов предложенных на занятии.

In [15]:
url =  "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"
!wget $url

--2021-10-23 18:22:50--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1,4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1,41M   676KB/s    in 2,1s    

2021-10-23 18:22:53 (676 KB/s) - ‘data.csv’ saved [1475504/1475504]



2. Выведите несколько первых строк таблицы. 

In [64]:
df = pd.read_csv('data.csv')
df.head().T

0  \
Make                                                 BMW   
Model                                         1 Series M   
Year                                                2011   
Engine Fuel Type             premium unleaded (required)   
Engine HP                                          335.0   
Engine Cylinders                                     6.0   
Transmission Type                                 MANUAL   
Driven_Wheels                           rear wheel drive   
Number of Doors                                      2.0   
Market Category    Factory Tuner,Luxury,High-Performance   
Vehicle Size                                     Compact   
Vehicle Style                                      Coupe   
highway MPG                                           26   
city mpg                                              19   
Popularity                                          3916   
MSRP                                               46135   

                                             1                            2  \
Make                                       BMW                          BMW   
Model                                 1 Series                     1 Series   
Year                                      2011                         2011   
Engine Fuel Type   premium unleaded (required)  premium unleaded (required)   
Engine HP                                300.0                        300.0   
Engine Cylinders                           6.0                          6.0   
Transmission Type                       MANUAL                       MANUAL   
Driven_Wheels                 rear wheel drive             rear wheel drive   
Number of Doors                            2.0                          2.0   
Market Category             Luxury,Performance      Luxury,High-Performance   
Vehicle Size                           Compact                      Compact   
Vehicle Style                      Convertible                        Coupe   
highway MPG                                 28                           28   
city mpg                                    19                           20   
Popularity                                3916                         3916   
MSRP                                     40650                        36350   

                                             3                            4  
Make                                       BMW                          BMW  
Model                                 1 Series                     1 Series  
Year                                      2011                         2011  
Engine Fuel Type   premium unleaded (required)  premium unleaded (required)  
Engine HP                                230.0                        230.0  
Engine Cylinders                           6.0                          6.0  
Transmission Type                       MANUAL                       MANUAL  
Driven_Wheels                 rear wheel drive             rear wheel drive  
Number of Doors                            2.0                          2.0  
Market Category             Luxury,Performance                       Luxury  
Vehicle Size                           Compact                      Compact  
Vehicle Style                            Coupe                  Convertible  
highway MPG                                 28                           28  
city mpg                                    18                           18  
Popularity                                3916                         3916  
MSRP                                     29450                        34500

3. Отфильруйте машины по марке и оставьте только строки с автомобилями BMW. 

In [94]:
df_bmw = df[df['Make'] == 'BMW']
df_bmw.T

0      \
Make                                                 BMW   
Model                                         1 Series M   
Year                                                2011   
Engine Fuel Type             premium unleaded (required)   
Engine HP                                          335.0   
Engine Cylinders                                     6.0   
Transmission Type                                 MANUAL   
Driven_Wheels                           rear wheel drive   
Number of Doors                                      2.0   
Market Category    Factory Tuner,Luxury,High-Performance   
Vehicle Size                                     Compact   
Vehicle Style                                      Coupe   
highway MPG                                           26   
city mpg                                              19   
Popularity                                          3916   
MSRP                                               46135   

                                         1                            2      \
Make                                       BMW                          BMW   
Model                                 1 Series                     1 Series   
Year                                      2011                         2011   
Engine Fuel Type   premium unleaded (required)  premium unleaded (required)   
Engine HP                                300.0                        300.0   
Engine Cylinders                           6.0                          6.0   
Transmission Type                       MANUAL                       MANUAL   
Driven_Wheels                 rear wheel drive             rear wheel drive   
Number of Doors                            2.0                          2.0   
Market Category             Luxury,Performance      Luxury,High-Performance   
Vehicle Size                           Compact                      Compact   
Vehicle Style                      Convertible                        Coupe   
highway MPG                                 28                           28   
city mpg                                    19                           20   
Popularity                                3916                         3916   
MSRP                                     40650                        36350   

                                         3                            4      \
Make                                       BMW                          BMW   
Model                                 1 Series                     1 Series   
Year                                      2011                         2011   
Engine Fuel Type   premium unleaded (required)  premium unleaded (required)   
Engine HP                                230.0                        230.0   
Engine Cylinders                           6.0                          6.0   
Transmission Type                       MANUAL                       MANUAL   
Driven_Wheels                 rear wheel drive             rear wheel drive   
Number of Doors                            2.0                          2.0   
Market Category             Luxury,Performance                       Luxury   
Vehicle Size                           Compact                      Compact   
Vehicle Style                            Coupe                  Convertible   
highway MPG                                 28                           28   
city mpg                                    18                           18   
Popularity                                3916                         3916   
MSRP                                     29450                        34500   

                                         5                            6      \
Make                                       BMW                          BMW   
Model                                 1 Series                     1 Series   
Year                                      2012                         2012   
Engine Fuel Type   premium

4. Найдите среднюю стоимость автомобиля BMW и выведите данное значение с точность до двух знаком после запятой.

In [81]:
res = sum(df_bmw.MSRP) / len(df_bmw.MSRP)
print(round(res, 2))

61546.76


5. Определите каких автомобилей больше с ручной коробокой передач или автоматической?

In [96]:
len(df_bmw[df_bmw['Transmission Type'] != 'MANUAL']) > len(df_bmw[df_bmw['Transmission Type'] == 'MANUAL'])

True